# Generated by Django 4.1 on 2023-05-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="slug",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(fields=["slug"], name="neighbourho_slug_bd6673_idx"),
        ),
    ]
