# Generated by Django 4.1 on 2023-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0004_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.CharField(
                blank=True, default="", max_length=100, null=True, unique=True
            ),
        ),
    ]
