# Generated by Django 4.1 on 2023-05-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0005_make_team_slug_unique"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="team",
            new_name="neighbourho_slug_4a851f_idx",
            old_name="neighbourho_slug_bd6673_idx",
        ),
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
