# Generated by Django 4.1 on 2023-05-18 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0006_add_team_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                related_name="teams",
                related_query_name="team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
