# Generated by Django 4.1 on 2023-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0010_add_user_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
