# Generated by Django 4.1 on 2023-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0014_add_team_admin_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="domain",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("new_team", "New Team"),
                    ("login", "Login"),
                ],
                max_length=50,
            ),
        ),
    ]
