# Generated by Django 4.1 on 2023-06-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0015_alter_token_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
