# Generated by Django 4.1 on 2023-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0016_membership_rejected"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("area_type", models.CharField(max_length=20)),
                ("mapit_id", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["area_type"], name="neighbourho_area_ty_7a1877_idx"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="areas",
            field=models.ManyToManyField(
                related_name="teams",
                related_query_name="teams",
                to="neighbourhood.area",
            ),
        ),
    ]
