# Generated by Django 4.2.15 on 2024-08-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0020_team_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="has_rich_description",
            field=models.BooleanField(
                default=False, help_text="True if description is raw html"
            ),
        ),
    ]
