# Generated by Django 4.2.15 on 2024-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0021_challenge_rich_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="short_description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
