# Generated by Django 4.1 on 2024-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0022_public_challenge_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(
                help_text="Detailed text content (plain text or HTML) shown to signed-in team members"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="has_rich_description",
            field=models.BooleanField(
                default=False, help_text="True if description is raw HTML"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive challenges are not displayed anywhere"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Private challenges are shown only to signed-in team members",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="short_description",
            field=models.CharField(
                blank=True,
                help_text="A one line summary of the challenge, suitable for public view",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="template",
            field=models.CharField(
                help_text="Default: neighbourhood/challenges/_default.html",
                max_length=300,
            ),
        ),
    ]
