# Generated by Django 4.1 on 2024-09-25 18:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("neighbourhood", "0023_alter_challenge_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="boundary",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
